GET http://localhost:8080/test/hello/0 HTTP/1.1

###
GET http://localhost:8080/test/hello/1 HTTP/1.1

###
POST http://localhost:8080/login HTTP/1.1
Content-Type: application/json; charset=UTF-8

{
  "name": "sample",
  "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}